backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"     # where images go in the project folder
public_folder: "/images/uploads"   # how they appear on the website

collections:
  - name: "projects"
    label: "Projects"
    folder: "projects"     # creates .md files here
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "PDF File", name: "pdf", widget: "file", media_library: { allow_multiple: false }, required: false }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Description", name: "body", widget: "markdown" }
